export const types = {
    FETCH_NEWS: "FETCH/NEWS",
    ADD_NEWS: "ADD/NEWS",
    ERROR_NEWS: "ERROR/NEWS",
    ADD_NEWS_BY_CAT: "ADD/NEWS/BY/CAT",
    FETCH_NEWS_BY_CAT: "FETCH/NEWS/BY/CAT"
  }; 


